# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nctl < Formula
  desc "Interact with Nine API resources."
  homepage "https://github.com/ninech/nctl"
  version "1.2.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ninech/nctl/releases/download/v1.2.1/nctl_1.2.1_darwin_amd64.tar.gz"
      sha256 "8251b765a6fe780b2a8cf1287a62614e0bad739d7259ec6bd2bd43ca30f47d1c"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ninech/nctl/releases/download/v1.2.1/nctl_1.2.1_darwin_arm64.tar.gz"
      sha256 "43f5e432744fe6026df7428f77f0400c084e0ff1749fc5ebb8f30792a4226a91"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ninech/nctl/releases/download/v1.2.1/nctl_1.2.1_linux_arm64.tar.gz"
      sha256 "84ab62aa11a9abc87b7ea8481c263e3c22eaccf4e2007adfdf2a0e553c4328b1"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ninech/nctl/releases/download/v1.2.1/nctl_1.2.1_linux_amd64.tar.gz"
      sha256 "3c95253eeeae2d55210a69be0230b27ea8e4800590d7ac814fce071ee23de302"

      def install
        bin.install "nctl"
      end
    end
  end
end
